[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "pyritrix3"
version = "0.0.1"
authors = [
  { name="Emilian Zawrotny", email="emilian@zawrotny.pl" },
]
description = "A simple wrapper around Heritrix3' REST API"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/obrotowy/pyritrix3"
Issues = "https://github.com/obrotowy/pyritrix3/issues"
